coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 5%
        base: auto
        flags:
          - unit

ignore:
  - "numbertype_string.go"
  - "type_string.go"
  - "nodetype_string.go"
  # todo: add tests in the future
  - "ast_utils.go"
  - "validator_utils.go"