// Code generated by "stringer -type=NodeType"; DO NOT EDIT.

package astjson

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Number-0]
	_ = x[Null-1]
	_ = x[String-2]
	_ = x[Bool-3]
	_ = x[Object-4]
	_ = x[Array-5]
}

const _NodeType_name = "NumberNullStringBoolObjectArray"

var _NodeType_index = [...]uint8{0, 6, 10, 16, 20, 26, 31}

func (i NodeType) String() string {
	if i >= NodeType(len(_NodeType_index)-1) {
		return "NodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeType_name[_NodeType_index[i]:_NodeType_index[i+1]]
}
