// Code generated by "stringer -type=Type"; DO NOT EDIT.

package astjson

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant KvMap have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tkWhiteSpace-0]
	_ = x[tkString-1]
	_ = x[tkNumber-2]
	_ = x[tkBool-3]
	_ = x[tkNull-4]
	_ = x[tkEOF-5]
	_ = x[tkObjectStart-6]
	_ = x[tkObjectEnd-7]
	_ = x[tkArrayStart-8]
	_ = x[tkArrayEnd-9]
	_ = x[tkComma-10]
	_ = x[tkColon-11]
}

const _Type_name = "tkWhiteSpacetkStringtkNumbertkBooltkNulltkEOFtkObjectStarttkObjectEndtkArrayStarttkArrayEndtkCommatkColon"

var _Type_index = [...]uint8{0, 12, 20, 28, 34, 40, 45, 58, 69, 81, 91, 98, 105}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
